### ISSUE TITLE
el psy congroo

### ISSUE THREAD

**Issue by kilesduli** [Anirban166/World-Lines#1]

**Comment by Anirban166** [comment]
**?**
![12](https://user-images.githubusercontent.com/30123691/98157739-c7a67200-1eff-11eb-9ee1-14f11e51ef42.png)
**. . .**
![13](https://user-images.githubusercontent.com/30123691/98157752-cecd8000-1eff-11eb-9230-68eefc34cddb.png)

<img width="761" alt="Screenshot 2020-10-11 at 9 49 58 PM" src="https://user-images.githubusercontent.com/30123691/95683941-c4271000-0c0b-11eb-8102-33aee0eff434.png">
