### ISSUE TITLE
Fix random number generation 

### ISSUE THREAD

**Issue by Anirban166** [Anirban166/World-Lines#3]
<img width="1036" alt="Screenshot 2020-12-01 at 12 46 04 PM" src="https://user-images.githubusercontent.com/30123691/100708945-37aaf980-33d3-11eb-9a9f-92b44b6da497.png">

Currently, the [code](https://github.com/Anirban166/World-Lines/blob/master/src/WorldLines.go) seeds a value based on the time (within the `divergenceNumberGenerator` function), which is fixed i.e. random numbers are not being generated in each function call.

Your goal is to fix it such that it properly generates random values.

**Comment by shobhit10058** [comment]
I had a fix about this .Should I send a PR?
