### ISSUE TITLE
Adding golangci-lint

### ISSUE THREAD

**Issue by iamrajiv** [Anirban166/World-Lines#6]

**Comment by iamrajiv** [comment]
@Anirban166 I want to work on this issue.

**Comment by Anirban166** [comment]
> `golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports yaml config, has integrations with all major IDE and has dozens of linters included.

Interesting, seems like a good fit!

> @Anirban166 I want to work on this issue.

Sure, go ahead 👍
